; Proyecto PlatformIO del nodo de calidad del agua
; Elegir el entorno según la placa (y la misma placa en include/config.h)
;   Compilar:          pio run -e lilygo_t3_v1_6_1
;   Grabar:            pio run -e lilygo_t3_v1_6_1 -t upload
;   Monitor serie:     pio device monitor

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
; Versiones fijas: la API LoRaWAN de RadioLib cambia entre versiones
lib_deps =
    jgromes/RadioLib@7.8.1
    adafruit/Adafruit ADS1X15@2.6.2
    4-20ma/ModbusMaster@2.0.1
    olikraus/U8g2@2.36.18
build_flags = -Wall

[env:lilygo_t3_v1_6_1]
board = ttgo-lora32-v21
build_flags = ${env.build_flags} -DPLACA_LILYGO_T3_V1_6_1

[env:lilygo_t3s3_sx1262]
board = esp32-s3-devkitc-1
build_flags = ${env.build_flags} -DPLACA_LILYGO_T3S3_SX1262 -DARDUINO_USB_CDC_ON_BOOT=1
